### PR TITLE
Fixing returns error type

### LINKED ISSUE #23: Returns an error `ErrorInternalServerError` instead of `ErrorUnauthorized`
Returns an error `ErrorInternalServerError` instead of `ErrorUnauthorized` when the key cannot be extracted

### PR DESCRIPTION
**Pull request by TheAwiteb**
Will closes #23

### CODE REVIEW

**Comment by AaronErhardt** [comment]
I understand the idea, but it's still debatable whether this is desired or should be changed in the [`extract`](https://github.com/AaronErhardt/actix-governor/blob/main/src/key_extractor.rs#L18) method.

Some would say that it's a server error if the key can't be extracted, in other cases it has to do with authorization. This should probably be up to the `KeyExtractor` implementation to figure this out. If `extract` returned `Result<Self::Key, actix_web::Error>`, the key extractor would be in charge of setting the correct behavior which IMO would be the better solution.

**Comment by TheAwiteb** [comment]
I think that it's good, `response_error` method will use it when extract failed

**Comment by TheAwiteb** [comment]
it's missing a tests, i will add it, don't merge it

File: src/lib.rs [hunk 1]
```diff
@@ -97,6 +97,16 @@
 //!
 //! Check out the [custom_key](https://github.com/AaronErhardt/actix-governor/blob/main/examples/custom_key.rs) example to see how a custom key extractor can be implemented.
 //!
+//! # Customize response error
+//!
+//! By default, response error it's [`INTERNAL_SERVER_ERROR`] but if you want to change it you can override [`response_error`] function and return the error as you want
```
Comment (AaronErhardt) [inline src/lib.rs]: My suggestion for improving the readability of the docs:

 //! By default, the response error generates an [`INTERNAL_SERVER_ERROR`] but if you want you can override the [`response_error`] function to return a custom error.

File: src/key_extractor.rs [hunk 2]
```diff
@@ -17,6 +16,14 @@ pub trait KeyExtractor: Clone {
     /// Extraction method
     fn extract(&self, req: &ServiceRequest) -> Result<Self::Key, Self::KeyExtractionError>;
 
+    /// Error function, will pass [`Self::KeyExtractionError`] to it to return the response error
+    /// when the [`Self::extract`] failed [Read more]
+    ///
+    /// [Read more]: https://docs.rs/actix-web/4.1.0/actix_web/error/index.html#functions
+    fn response_error(&self, err: &Self::KeyExtractionError) -> actix_web::Error {
```
Comment (AaronErhardt) [inline src/key_extractor.rs]: Is there a particular reason why this only gets a reference to the error? I think this should be an owned type instead.

**Review by AaronErhardt — CHANGES_REQUESTED** [review]
Looks good, just a few minor things could be improved.

File: src/key_extractor.rs (hunk 2 above)
Comment (TheAwiteb) [reply src/key_extractor.rs]: I said that it could be developed in the future, we need the error, so I passed a reference

Comment (AaronErhardt) [reply src/key_extractor.rs]: I'm sorry, I don't understand your reasoning. It's not a big deal of course, but when we can pass is as owned type we should to prevent unnecessary cloning. Also, I don't understand what would change in the future to prevent this.

**Review by AaronErhardt — APPROVED** [review]
Looks good to me. Is it ready to merge?

**Comment by TheAwiteb** [comment]
> Is it ready to merge?

Yes ready 🎉

**Comment by AaronErhardt** [comment]
Alright, thanks for your contribution!
